const places=[
 {id:"testaccio",name:"Monte Testaccio",subtitle:"La montagna fatta di storie",type:"Memoria",kind:"memory",route:"city",icon:"🏺",x:16,y:23,description:"Una collina costruita dall'uomo con milioni di frammenti di anfore romane. Ogni coccio racconta commerci, viaggi e abitudini dell'antica Roma.",story:"Non è solo una collina: è un archivio a cielo aperto dell'economia mediterranea.",missionTitle:"Leggi un frammento",mission:"Osserva forme, colori e stratificazioni. Disegna un frammento e immagina quale viaggio potrebbe aver compiuto."},
 {id:"emporium",name:"Emporium e porto fluviale",subtitle:"Roma arrivava dal Tevere",type:"Archeologia",kind:"memory",route:"city",icon:"⚓",x:31,y:43,description:"Qui approdavano merci provenienti da tutto il Mediterraneo. Il fiume era una grande strada d'acqua che nutriva e collegava la città.",story:"Prima delle ferrovie e dei camion, il Tevere era la porta commerciale di Roma.",missionTitle:"Traccia la rotta",mission:"Scegli una merce dell'antichità e disegna sulla mappa il viaggio dal suo luogo d'origine fino a Roma."},
 {id:"centrale",name:"Centrale Montemartini",subtitle:"Macchine e statue nello stesso racconto",type:"Cultura",kind:"culture",route:"city",icon:"⚙️",x:46,y:24,description:"Una ex centrale elettrica ospita oggi capolavori dell'arte antica. Il contrasto tra turbine e statue rende visibile il dialogo tra epoche diverse.",story:"La città non cancella sempre il passato: a volte lo mette in conversazione con il presente.",missionTitle:"Cerca il contrasto",mission:"Trova due elementi di epoche diverse. Fotografali o descrivili e spiega perché funzionano bene insieme."},
 {id:"gazometro",name:"Gazometro",subtitle:"L'icona industriale di Ostiense",type:"Città",kind:"culture",route:"city",icon:"◉",x:60,y:39,description:"La grande struttura metallica è diventata il simbolo del quartiere industriale. Oggi parla di trasformazione urbana, creatività e rigenerazione.",story:"Un'infrastruttura può smettere di funzionare e continuare a dare identità a un luogo.",missionTitle:"Immagina il futuro",mission:"Progetta un nuovo uso culturale o ambientale per uno spazio industriale dismesso del quartiere."},
 {id:"streetart",name:"Street art Ostiense",subtitle:"I muri prendono la parola",type:"Arte urbana",kind:"culture",route:"city",icon:"🎨",x:71,y:54,description:"Murales e interventi di arte urbana trasformano facciate e passaggi in pagine pubbliche. Colori e simboli raccontano comunità, conflitti e speranze.",story:"Un muro può separare, ma può anche diventare uno spazio di racconto condiviso.",missionTitle:"Decifra il messaggio",mission:"Scegli un simbolo o un colore ricorrente e scrivi in una frase il messaggio che ti trasmette."},
 {id:"schuster",name:"Parco Schuster",subtitle:"Un giardino tra storia e quartiere",type:"Natura",kind:"nature",route:"nature",icon:"🌳",x:84,y:76,description:"Uno spazio verde vicino alla Basilica, luogo di incontro e osservazione. Alberi, prati e piccola fauna urbana mostrano come la natura abiti la città.",story:"Anche un parco urbano è un ecosistema: piccolo, fragile e pieno di relazioni.",missionTitle:"Caccia ai colori",mission:"Trova cinque tonalità naturali diverse senza raccogliere nulla. Descrivile o fotografale nel tuo taccuino."},
 {id:"basilica",name:"Basilica di San Paolo",subtitle:"Un luogo attraversato dai secoli",type:"Patrimonio",kind:"memory",route:"nature",icon:"✦",x:90,y:52,description:"La Basilica di San Paolo fuori le Mura è un riferimento storico, artistico e spirituale del territorio. Il suo paesaggio unisce memoria, architettura e comunità.",story:"Custodire un luogo significa riconoscerne il valore per persone anche molto diverse tra loro.",missionTitle:"Osserva il dettaglio",mission:"Individua un motivo geometrico o naturale nell'architettura e trasformalo in un piccolo pattern grafico."},
 {id:"tevere",name:"Parco Tevere Marconi",subtitle:"Il fiume come ecosistema",type:"Natura",kind:"nature",route:"nature",icon:"🌊",x:69,y:25,description:"Lungo il Tevere convivono acqua, vegetazione ripariale, uccelli e tracce della presenza umana. È un corridoio ecologico nel cuore della città.",story:"Il fiume non è solo uno sfondo: è un organismo vivo che collega territori e specie.",missionTitle:"Ascolta il paesaggio",mission:"Resta in silenzio per un minuto. Conta i suoni naturali e quelli prodotti dall'uomo, poi confrontali."}
];

const state={route:"all",completed:new Set(JSON.parse(localStorage.getItem("custodi-completed")||"[]")),selected:null};
const $=s=>document.querySelector(s);
const els={markers:$("#map-markers"),next:$("#next-card"),visible:$("#visible-count"),dialog:$("#place-dialog"),headerProgress:$("#header-progress"),stampCount:$("#stamp-count"),stamps:$("#stamp-grid"),progressLabel:$("#progress-label"),progressLine:$("#progress-line"),custodian:$("#custodian-number"),toast:$("#toast")};

function filtered(){return places.filter(p=>state.route==="all"||p.route===state.route)}
function numberFor(id){return String(places.findIndex(p=>p.id===id)+1).padStart(2,"0")}
function showToast(text){els.toast.textContent=text;els.toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>els.toast.classList.remove("show"),2400)}
function beep(freq=520){try{const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.12)}catch(e){}}

function renderMap(){
 const visible=filtered(); els.visible.textContent=`${visible.length} ${visible.length===1?"tappa":"tappe"}`;
 els.markers.innerHTML=places.map(p=>`<button class="map-marker ${p.kind} ${state.completed.has(p.id)?"completed":""} ${visible.includes(p)?"":"hidden"}" style="left:${p.x}%;top:${p.y}%" data-id="${p.id}" aria-label="Apri ${p.name}">${state.completed.has(p.id)?"✓":numberFor(p.id).replace(/^0/,"")}<span class="marker-label">${p.name}</span></button>`).join("");
 document.querySelectorAll(".map-marker:not(.hidden)").forEach(b=>{b.addEventListener("click",()=>openPlace(b.dataset.id));b.addEventListener("mouseenter",()=>renderNext(b.dataset.id))});
 renderNext((visible.find(p=>!state.completed.has(p.id))||visible[0]).id);
}
function renderNext(id){const p=places.find(x=>x.id===id);els.next.innerHTML=`<div class="place-number"><span>Prossima tappa</span><strong>${numberFor(p.id)}</strong></div><div class="place-icon">${p.icon}</div><h3>${p.name}</h3><p class="next-subtitle">${p.subtitle}</p><p>${p.description.slice(0,145)}…</p><button class="button button-sun" data-open="${p.id}">Scopri la tappa <span>→</span></button>`;els.next.querySelector("button").addEventListener("click",()=>openPlace(p.id))}
function openPlace(id){const p=places.find(x=>x.id===id);state.selected=p;$("#dialog-index").textContent=`TAPPA ${numberFor(id)}`;$("#dialog-type").textContent=p.type;$("#dialog-name").textContent=p.name;$("#dialog-subtitle").textContent=p.subtitle;$("#dialog-description").textContent=p.description;$("#dialog-story").textContent=`“${p.story}”`;$("#mission-symbol").textContent=p.icon;$("#dialog-mission-title").textContent=p.missionTitle;$("#dialog-mission").textContent=p.mission;const done=state.completed.has(id),btn=$("#complete-mission");btn.disabled=done;btn.innerHTML=done?'Missione completata <span>✓</span>':'Completa missione <span>＋</span>';els.dialog.showModal();beep(430)}
function completeMission(){if(!state.selected||state.completed.has(state.selected.id))return;state.completed.add(state.selected.id);localStorage.setItem("custodi-completed",JSON.stringify([...state.completed]));renderAll();const btn=$("#complete-mission");btn.disabled=true;btn.innerHTML='Missione completata <span>✓</span>';beep(760);showToast(`Timbro conquistato: ${state.selected.name}`);if(state.completed.size===places.length)setTimeout(()=>showToast("Passaporto completo: sei Custode del Territorio! ✦"),1000)}
function renderPassport(){const n=state.completed.size,pct=Math.round(n/places.length*100);els.headerProgress.textContent=`${n}/${places.length}`;els.stampCount.textContent=`${n} ${n===1?"timbro":"timbri"}`;els.progressLabel.textContent=`${pct}%`;els.progressLine.style.width=`${pct}%`;els.custodian.textContent=n?String(1047+n*37).padStart(4,"0"):"----";els.stamps.innerHTML=places.map((p,i)=>`<div class="stamp ${state.completed.has(p.id)?"complete":""}" style="--tilt:${[-4,3,-2,5,2,-5,4,-3][i]}deg"><span>${state.completed.has(p.id)?p.icon:"·"}</span><strong>${state.completed.has(p.id)?p.name:"Da scoprire"}</strong></div>`).join("")}
function renderAll(){renderMap();renderPassport()}

document.querySelectorAll(".route-tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".route-tab").forEach(t=>{t.classList.remove("active");t.setAttribute("aria-selected","false")});tab.classList.add("active");tab.setAttribute("aria-selected","true");state.route=tab.dataset.route;renderMap();beep(500)}));
$("#close-dialog").addEventListener("click",()=>els.dialog.close());els.dialog.addEventListener("click",e=>{if(e.target===els.dialog)els.dialog.close()});$("#complete-mission").addEventListener("click",completeMission);
const intro=$("#intro-dialog");$("#open-intro").addEventListener("click",()=>intro.showModal());$("#close-intro").addEventListener("click",()=>intro.close());$("#intro-start").addEventListener("click",()=>{intro.close();$("#esplora").scrollIntoView({behavior:"smooth"})});intro.addEventListener("click",e=>{if(e.target===intro)intro.close()});
$("#passport-mini").addEventListener("click",()=>$("#missioni").scrollIntoView({behavior:"smooth"}));$("#reset-progress").addEventListener("click",()=>{if(!confirm("Vuoi cancellare tutti i timbri e ricominciare?"))return;state.completed.clear();localStorage.removeItem("custodi-completed");renderAll();showToast("Passaporto azzerato")});
renderAll();
